# **Import** **Train,Test,Split** **Cleaning**

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [ ]:
from sklearn.neural_network import MLPClassifier


In [ ]:
import pandas as pd
import numpy as np
import math
import seaborn as sns #Data Visualization
import matplotlib.pyplot as plt

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix , accuracy_score, precision_score, recall_score ,f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/data/flood_risk_dataset_india.csv")

In [ ]:
df.columns


Index(['Latitude', 'Longitude', 'Rainfall (mm)', 'River Discharge (m³/s)',
       'Water Level (m)', 'Elevation (m)', 'Historical Floods',
       'Flood Occurred'],
      dtype='object')

In [ ]:
#df = df[['Latitude', 'Longitude', 'Rainfall (mm)', 'River Discharge (m³/s)', 'Water Level (m)',
       #'Elevation (m)', 'Historical Floods', 'Flood Occurred']]

In [ ]:
df.head(5)

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.isnull().sum()

# Graphs

## Outlier Checking (Box Plot)

In [ ]:
columns = df.columns
for i in range(8):
  fig = plt.figure(figsize = (10,5))
  ax = fig.gca()
  df.boxplot(column=columns[i], by= "Flood Occurred", ax=ax)
  plt.ylabel(columns[i])
  plt.xlabel("Flood Occurred")

## Pie Chart

In [ ]:
ax1 = df.groupby(["Land Cover"])["Flood Occurred"].sum().plot.pie(
    figsize = (4,5),
    fontsize = 14
)
ax.set_title("Total Occurences of Floods according to Land Cover type" , fontsize = 10)
ax1.set_xlabel("")
ax1.set_ylabel("")

In [ ]:
ax1 = df.groupby(["Soil Type"])["Flood Occurred"].sum().plot.pie(
    figsize = (4,5),
    fontsize = 14
)
ax.set_title("Total Occurences of Floods according to Soil type" , fontsize = 10)
ax1.set_xlabel("")
ax1.set_ylabel("")

## Histograms

In [ ]:
ax = df.groupby(["Land Cover"])["Flood Occurred"].sum().plot.bar()
ax.set_title("Total Occurences of Floods according to Land Cover type" , fontsize = 10)

In [ ]:
ax = df.groupby(["Soil Type"])["Flood Occurred"].sum().plot.bar()
ax.set_title("Total Occurences of Floods according to Soil type" , fontsize = 10)

# Encoding

In [ ]:
df["Agricultural"] = np.where(df["Land Cover"] == "Agricultural" , 1,0)
df["Desert"] = np.where(df["Land Cover"] == "Desert" , 1,0)
df["Forest"] = np.where(df["Land Cover"] == "Forest" , 1,0)
df["Urban"] = np.where(df["Land Cover"] == "Urban" , 1,0)
df["Water"] = np.where(df["Land Cover"] == "Water Body" , 1,0)

df.drop(columns=['Land Cover'],axis = 1, inplace = True)
df.head()

Latitude  Longitude  Rainfall (mm)  Temperature (°C)  Humidity (%)  \
0  18.861663  78.835584     218.999493         34.144337     43.912963   
1  35.570715  77.654451      55.353599         28.778774     27.585422   
2  29.227824  73.108463     103.991908         43.934956     30.108738   
3  25.361096  85.610733     198.984191         21.569354     34.453690   
4  12.524541  81.822101     144.626803         32.635692     36.292267   

   River Discharge (m³/s)  Water Level (m)  Elevation (m) Soil Type  \
0             4236.182888         7.415552     377.465433      Clay   
1             2472.585219         8.811019    7330.608875      Peat   
2              977.328053         4.631799    2205.873488      Loam   
3             3683.208933         2.891787    2512.277800     Sandy   
4             2093.390678         3.188466    2001.818223      Loam   

   Population Density  Infrastructure  Historical Floods  Flood Occurred  \
0         7276.742184               1                  0               1   
1         6897.736956               0                  1               0   
2         4361.518494               1                  1               1   
3         6163.069701               1                  1               0   
4         6167.964591               1                  0               0   

   Agricultural  Desert  Forest  Urban  Water  
0             0       0       0      0      1  
1             0       0       1      0      0  
2             1       0       0      0      0  
3             0       1       0      0      0  
4             1       0       0      0      0

In [ ]:
df.columns

Index(['Latitude', 'Longitude', 'Rainfall (mm)', 'Temperature (°C)',
       'Humidity (%)', 'River Discharge (m³/s)', 'Water Level (m)',
       'Elevation (m)', 'Soil Type', 'Population Density', 'Infrastructure',
       'Historical Floods', 'Flood Occurred', 'Agricultural', 'Desert',
       'Forest', 'Urban', 'Water'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Latitude                10000 non-null  float64
 1   Longitude               10000 non-null  float64
 2   Rainfall (mm)           10000 non-null  float64
 3   Temperature (°C)        10000 non-null  float64
 4   Humidity (%)            10000 non-null  float64
 5   River Discharge (m³/s)  10000 non-null  float64
 6   Water Level (m)         10000 non-null  float64
 7   Elevation (m)           10000 non-null  float64
 8   Soil Type               10000 non-null  object 
 9   Population Density      10000 non-null  float64
 10  Infrastructure          10000 non-null  int64  
 11  Historical Floods       10000 non-null  int64  
 12  Flood Occurred          10000 non-null  int64  
 13  Agricultural            10000 non-null  int64  
 14  Desert                  10000 non-null 

In [ ]:
df["Peat"] = np.where(df["Soil Type"] == "Peat" , 1,0)
df["Loam"] = np.where(df["Soil Type"] == "Loam" , 1,0)
df["Sandy"] = np.where(df["Soil Type"] == "Sandy" , 1,0)
df["Clay"] = np.where(df["Soil Type"] == "Clay" , 1,0)
df["Silt"] = np.where(df["Soil Type"] == "Silt" , 1,0)

df.drop(columns=['Soil Type'],axis = 1, inplace = True)
df.head()

Latitude  Longitude  Rainfall (mm)  Temperature (°C)  Humidity (%)  \
0  18.861663  78.835584     218.999493         34.144337     43.912963   
1  35.570715  77.654451      55.353599         28.778774     27.585422   
2  29.227824  73.108463     103.991908         43.934956     30.108738   
3  25.361096  85.610733     198.984191         21.569354     34.453690   
4  12.524541  81.822101     144.626803         32.635692     36.292267   

   River Discharge (m³/s)  Water Level (m)  Elevation (m)  Population Density  \
0             4236.182888         7.415552     377.465433         7276.742184   
1             2472.585219         8.811019    7330.608875         6897.736956   
2              977.328053         4.631799    2205.873488         4361.518494   
3             3683.208933         2.891787    2512.277800         6163.069701   
4             2093.390678         3.188466    2001.818223         6167.964591   

   Infrastructure  ...  Agricultural  Desert  Forest  Urban  Water  Peat  \
0               1  ...             0       0       0      0      1     0   
1               0  ...             0       0       1      0      0     1   
2               1  ...             1       0       0      0      0     0   
3               1  ...             0       1       0      0      0     0   
4               1  ...             1       0       0      0      0     0   

   Loam  Sandy  Clay  Silt  
0     0      0     1     0  
1     0      0     0     0  
2     1      0     0     0  
3     0      1     0     0  
4     1      0     0     0  

[5 rows x 22 columns]

# Spliting

In [ ]:
x = df.drop(['Flood Occurred'], axis = 1)
y = df['Flood Occurred']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Scaling

In [ ]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train[0:30]

# Models

## Logistic Regression

In [ ]:
model = LogisticRegression(fit_intercept= True , max_iter = 10000)
model.fit(x_train,y_train)

LogisticRegression(max_iter=10000)

In [ ]:
model.coef_

array([[-0.01410992, -0.17579953, -0.00656507, -0.01322617, -0.0846682 ,
         0.00978532,  0.00760269]])

In [ ]:
model.intercept_

array([0.14878701])

In [ ]:
train_pred_prob = model.predict_proba(x_train)
test_pred_prob = model.predict_proba(x_test)

In [ ]:
print(train_pred_prob)

[[0.48679278 0.51320722]
 [0.50489994 0.49510006]
 [0.5208595  0.4791405 ]
 ...
 [0.50867911 0.49132089]
 [0.47409429 0.52590571]
 [0.49808335 0.50191665]]


In [ ]:
print(test_pred_prob)

[[0.51395011 0.48604989]
 [0.47719499 0.52280501]
 [0.50146433 0.49853567]
 ...
 [0.5127809  0.4872191 ]
 [0.51020067 0.48979933]
 [0.51091284 0.48908716]]


In [ ]:
train_class_pred = model.predict(x_train)
test_class_pred = model.predict(x_test)

In [ ]:
print(train_class_pred)

[1 0 0 ... 0 1 1]


In [ ]:
print(test_class_pred)

[0 1 0 ... 0 0 0]


### Scores

#### Accuracy Score

In [ ]:
train_accuracy = accuracy_score(train_class_pred , y_train)
test_accuracy = accuracy_score(test_class_pred , y_test)

In [ ]:
print(train_accuracy)

0.509


In [ ]:
print(test_accuracy)

0.4905


#### Precision Score

In [ ]:
train_precision = precision_score(train_class_pred ,y_train)
test_precision = precision_score(test_class_pred , y_test)


In [ ]:
train_precision

0.5625777556606121

In [ ]:
test_precision

0.546242774566474

#### F1 Score

In [ ]:
train_f1 = f1_score(train_class_pred ,y_train)
test_f1 = f1_score(test_class_pred , y_test)

In [ ]:
train_f1

0.5351479289940828

In [ ]:
test_f1

0.5267069205759406

#### Recall Score

In [ ]:
train_recall = recall_score(train_class_pred ,y_train)
test_recall = recall_score(test_class_pred , y_test)

In [ ]:
train_recall

0.5102685624012638

In [ ]:
test_recall

0.5085201793721973

#### Confusion Matrix

In [ ]:
labels = ['Retained','Churn']
train_cm = confusion_matrix(y_train , train_class_pred)

In [ ]:
train_cm

array([[1811, 2170],
       [1758, 2261]])

## Decision Tree

In [ ]:
flood_outcome_classifier = DecisionTreeClassifier(criterion ='entropy' ,max_leaf_nodes=10,  random_state = 0)
flood_outcome_classifier.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_leaf_nodes=10, random_state=0)

In [ ]:
train_class_dt_pred = flood_outcome_classifier.predict(x_train)
test_class_dt_pred = flood_outcome_classifier.predict(x_test)

In [ ]:
yc_train_pred = flood_outcome_classifier.predict(x_train)

In [ ]:
yc_train_pred

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
yc_test_pred = flood_outcome_classifier.predict(x_test)

In [ ]:
yc_test_pred

array([1, 1, 1, ..., 1, 1, 1])

### Scores

#### Accuracy Score

In [ ]:
accuracy_score(y_test,yc_test_pred)

0.5135

In [ ]:
accuracy_score(y_train,yc_train_pred)

0.524625

#### Recall Score

In [ ]:
recall_score(y_test,yc_test_pred)

0.9046242774566474

In [ ]:
recall_score(y_train,yc_train_pred)

0.9263498382682259

#### Precision Score

In [ ]:
precision_score(y_test,yc_test_pred)

0.5179260893546608

In [ ]:
precision_score(y_train,yc_train_pred)

0.5149377593360995

#### F1 Score

In [ ]:
f1_score(y_test,yc_test_pred)

0.658716239915819

In [ ]:
f1_score(y_train,yc_train_pred)

0.6619255044892879

#### Confusion Matrix

In [ ]:
labels = ['Safe','Flood Occured']
train_dt_cm = confusion_matrix(y_train , train_class_dt_pred)

In [ ]:
train_dt_cm

array([[ 474, 3507],
       [ 296, 3723]])

In [ ]:
labels = ['Safe','Flood Occured']
test_dt_cm = confusion_matrix(y_test , test_class_dt_pred)

In [ ]:
test_dt_cm

array([[ 88, 874],
       [ 99, 939]])

## Random Forest

In [ ]:
flood_outcome_rf_classifier = RandomForestClassifier(criterion ='entropy' ,max_leaf_nodes=100, random_state = 0)
flood_outcome_rf_classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_leaf_nodes=100, random_state=0)

In [ ]:
train_class_rf_pred = flood_outcome_classifier.predict(x_train)
test_class_rf_pred = flood_outcome_classifier.predict(x_test)

In [ ]:
yr_train_pred = flood_outcome_classifier.predict(x_train)
yr_train_pred

array([1, 0, 1, ..., 1, 0, 1])

In [ ]:
yr_test_pred = flood_outcome_classifier.predict(x_test)
yr_test_pred

array([1, 0, 0, ..., 1, 1, 0])

### Score

### Accuracy Score

In [ ]:
accuracy_score(y_test,yr_test_pred)

0.502

In [ ]:
accuracy_score(y_train,yr_train_pred)

1.0

### Precision Score

In [ ]:
precision_score(y_test,yr_test_pred)

0.521875

In [ ]:
precision_score(y_train,yr_train_pred)

1.0

### F1 Score

In [ ]:
f1_score(y_test,yr_test_pred)

0.5015015015015015

In [ ]:
f1_score(y_train,yr_train_pred)

1.0

### Recall Score

In [ ]:
recall_score(y_test,yr_test_pred)

0.48265895953757226

In [ ]:
recall_score(y_train,yr_train_pred)

1.0

### Confusion Matrix

In [ ]:
labels = ['Safe','Flood Occured']
train_rf_cm = confusion_matrix(y_train , train_class_rf_pred)
test_rf_cm = confusion_matrix(y_test , test_class_rf_pred)

In [ ]:
test_rf_cm

array([[503, 459],
       [537, 501]])

In [ ]:
train_rf_cm

array([[3981,    0],
       [   0, 4019]])

## Gradient Boost

In [ ]:
boost_outcome_rf_classifier = GradientBoostingClassifier(max_depth= 10,learning_rate=0.05, random_state=0)
boost_outcome_rf_classifier.fit(x_train,y_train)

GradientBoostingClassifier(learning_rate=0.05, max_depth=10, random_state=0)

In [ ]:
train_class_rf_pred = boost_outcome_rf_classifier.predict(x_train)
test_class_rf_pred = boost_outcome_rf_classifier.predict(x_test)

In [ ]:
yr_train_pred = boost_outcome_rf_classifier.predict(x_train)
yr_train_pred

array([1, 1, 1, ..., 1, 0, 1])

In [ ]:
yr_test_pred = boost_outcome_rf_classifier.predict(x_test)
yr_test_pred

array([1, 1, 0, ..., 0, 1, 0])

### Score

#### Accuracy Score

In [ ]:
accuracy_score(y_test,yr_test_pred)

0.4925

In [ ]:
accuracy_score(y_train,yr_train_pred)

0.95025

#### Precision Score

In [ ]:
precision_score(y_test,yr_test_pred)

0.5115810674723061

In [ ]:
precision_score(y_train,yr_train_pred)

0.9608042758971749

#### F1 Score

In [ ]:
f1_score(y_test,yr_test_pred)

0.5002461841457411

In [ ]:
f1_score(y_train,yr_train_pred)

0.9499245093105184

#### Recall Score

In [ ]:
recall_score(y_test,yr_test_pred)

0.48940269749518306

In [ ]:
recall_score(y_train,yr_train_pred)

0.9392883801940781

#### Confusion Matrix

In [ ]:
labels = ['Safe','Flood Occured']
train_rf_cm = confusion_matrix(y_train , train_class_rf_pred)
test_rf_cm = confusion_matrix(y_test , test_class_rf_pred)

In [ ]:
test_rf_cm

array([[477, 485],
       [530, 508]])

In [ ]:
train_rf_cm

array([[3827,  154],
       [ 244, 3775]])

## Hist Gradient Boost

In [ ]:
boost_outcome_rf_classifier = HistGradientBoostingClassifier(max_depth= 10,learning_rate=0.05, random_state=0)
boost_outcome_rf_classifier.fit(x_train,y_train)

HistGradientBoostingClassifier(learning_rate=0.05, max_depth=10, random_state=0)

In [ ]:
train_class_rf_pred = boost_outcome_rf_classifier.predict(x_train)
test_class_rf_pred = boost_outcome_rf_classifier.predict(x_test)

In [ ]:
yr_train_pred = boost_outcome_rf_classifier.predict(x_train)
yr_train_pred

array([1, 0, 1, ..., 1, 0, 0])

In [ ]:
yr_test_pred = boost_outcome_rf_classifier.predict(x_test)
yr_test_pred

array([0, 1, 0, ..., 0, 1, 0])

### Score

#### Accuracy Score

In [ ]:
accuracy_score(y_test,yr_test_pred)

0.4975

In [ ]:
accuracy_score(y_train,yr_train_pred)

0.778375

#### Precision Score

In [ ]:
precision_score(y_test,yr_test_pred)

0.5162241887905604

In [ ]:
precision_score(y_train,yr_train_pred)

0.7794922847187655

#### F1 Score

In [ ]:
f1_score(y_test,yr_test_pred)

0.5109489051094891

In [ ]:
f1_score(y_train,yr_train_pred)

0.7793952967525196

#### Recall Score

In [ ]:
recall_score(y_test,yr_test_pred)

0.5057803468208093

In [ ]:
recall_score(y_train,yr_train_pred)

0.7792983329186365

#### Confusion Matrix

In [ ]:
labels = ['Safe','Flood Occured']
train_rf_cm = confusion_matrix(y_train , train_class_rf_pred)
test_rf_cm = confusion_matrix(y_test , test_class_rf_pred)

In [ ]:
test_rf_cm

array([[470, 492],
       [513, 525]])

In [ ]:
train_rf_cm

array([[3095,  886],
       [ 887, 3132]])

# NEURAL NETWORK

In [ ]:
# Define the MLP model with appropriate hyperparameters
mlp_model = MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=0)

# Train the model
mlp_model.fit(x_train, y_train)


MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=0)

In [ ]:
# Make predictions
train_mlp_pred = mlp_model.predict(x_train)
test_mlp_pred = mlp_model.predict(x_test)

# Accuracy Score
train_accuracy_mlp = accuracy_score(y_train, train_mlp_pred)
test_accuracy_mlp = accuracy_score(y_test, test_mlp_pred)

# Precision Score
train_precision_mlp = precision_score(y_train, train_mlp_pred)
test_precision_mlp = precision_score(y_test, test_mlp_pred)

# F1 Score
train_f1_mlp = f1_score(y_train, train_mlp_pred)
test_f1_mlp = f1_score(y_test, test_mlp_pred)

# Recall Score
train_recall_mlp = recall_score(y_train, train_mlp_pred)
test_recall_mlp = recall_score(y_test, test_mlp_pred)

# Confusion Matrix
train_mlp_cm = confusion_matrix(y_train, train_mlp_pred)
test_mlp_cm = confusion_matrix(y_test, test_mlp_pred)

# Print results
print(f"Train Accuracy: {train_accuracy_mlp}")
print(f"Test Accuracy: {test_accuracy_mlp}")
print(f"Train Precision: {train_precision_mlp}")
print(f"Test Precision: {test_precision_mlp}")
print(f"Train F1 Score: {train_f1_mlp}")
print(f"Test F1 Score: {test_f1_mlp}")
print(f"Train Recall: {train_recall_mlp}")
print(f"Test Recall: {test_recall_mlp}")

print("\nConfusion Matrix (Train):")
print(train_mlp_cm)

print("\nConfusion Matrix (Test):")
print(test_mlp_cm)


Train Accuracy: 0.624125
Test Accuracy: 0.5055
Train Precision: 0.6123944913371835
Test Precision: 0.5220522052205221
Train F1 Score: 0.6471071470484685
Test F1 Score: 0.5397859469520707
Train Recall: 0.6859915401841254
Test Recall: 0.558766859344894

Confusion Matrix (Train):
[[2236 1745]
 [1262 2757]]

Confusion Matrix (Test):
[[431 531]
 [458 580]]
